apiVersion: v1
kind: Secret
metadata:
  name: basket-api-secret
  namespace: default
type: Opaque
data:
  EventBusSettings__HostAddress: YW1xcDovL2FkbWluOnBhc3N3b3JkQDEwLjEwMC4yMDMuMzM6NTY3Mg==
  CacheSettings__ConnectionString: MTAuOTYuNDAuMTg5OjYzNzk=
  GrpcSettings__DiscountUrl: aHR0cDovLzE5Mi4xNjguNDkuMjozMDAwMw==
#echo "devopscube" | base64
#powershell "[convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes('10.111.16.128'))"
#kubectl apply -f basket-api-secret.yaml
#kubectl apply -f basket-api-deployment.yaml