apiVersion: v1
kind: Secret
metadata:
  name: order-api-secret
  namespace: default
type: Opaque
data:
  ConnectionStrings__OrderingConnectionString: U2VydmVyPTEwLjEwMC4xMjcuMDtEYXRhYmFzZT1PcmRlckRiO1VzZXIgSWQ9c2E7UGFzc3dvcmQ9YWRtaW5AYWRtaW4xMjM0NTtUcnVzdFNlcnZlckNlcnRpZmljYXRlPVRydWU=
  EventBusSettings__HostAddress: YW1xcDovL2d1ZXN0Omd1ZXN0QDEwLjEwMC4yMDMuMzM6NTY3Mg==
#10.100.203.33: RabbitMQ
#powershell "[convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes('Server=10.100.127.0;Database=OrderDb;User Id=sa;Password=admin@admin12345;TrustServerCertificate=True'))"
#powershell "[convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes('amqp://guest:guest@10.100.203.33:5672'))"
#kubectl apply -f order-api-secret.yaml