apiVersion: apps/v1
kind: StatefulSet #Deployment #StatefulSet
metadata:
  name: ocelot-api-gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocelot-api-gateway
  template:
    metadata:
      labels:
        app: ocelot-api-gateway
    spec:
      containers:
      - name: ocelot-api-gateway
        image: srinivasanugu/ocelot-api-gateway-image:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ocelot-api-gateway-service
spec:
  type: NodePort
  ports:
    - port: 8002
      targetPort: 8080
      nodePort: 30002
  selector:
    app: ocelot-api-gateway