apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: default
type: Opaque
data:
  redis-user: YWRtaW4=  #[base64 encoded "admin"]
  redis-password: cGFzc3dvcmQ=  #[base64 encoded "password"]
#powershell "[convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes('admin'))"
---
apiVersion: apps/v1
kind: StatefulSet #Deployment
metadata:
  name: redis-deployment
  namespace: default
  labels:
    app: redis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
      - name: redis
        image: redis:6.2-alpine
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-password
        - name: REDIS_USERNAME
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-user
        #command: ["redis-server", "--requirepass", "$(REDIS_PASSWORD)", "--rename-command", "CONFIG", "", "--rename-command", "FLUSHDB", "", "--rename-command", "FLUSHALL", ""]
        volumeMounts:
        - name: redis-storage
          mountPath: /data
      volumes:
      - name: redis-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: default
  labels:
    app: redis-app
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-app
#kubectl apply -f 05-k8s-redis-deployment.yaml
#kubectl port-forward redis-deployment-0 6379:6379