apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
  namespace: default
type: Opaque
data:
  MSSQL_SA_PASSWORD: TmV3UGFzc3cwckRQQHNzdzByZDIwMjUh
  #powershell "[convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes('NewPassw0rDP@ssw0rd2025!'))"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlserver-pv
  namespace: default
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-pv-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sqlserver-deployment
  namespace: default
spec:
  serviceName: "sqlserver"
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver-app
  template:
    metadata:
      labels:
        app: sqlserver-app
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlserver-secret
              key: MSSQL_SA_PASSWORD
        volumeMounts:
        - name: sqlserver-storage
          mountPath: /var/opt/mssql
      volumes:
      - name: sqlserver-storage
        persistentVolumeClaim:
          claimName: sqlserver-pv-claim
  volumeClaimTemplates:
  - metadata:
      name: sqlserver-storage
      namespace: default
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 1433
    targetPort: 1433
  selector:
    app: sqlserver-app
    
#kubectl apply -f k8s-sqlserver-deployment.yaml
#kubectl delete -f k8s-sqlserver-deployment.yaml
#kubectl port-forward sqlserver-deployment-0 1433:1433
#Server=127.0.0.1,1433;User Id=sa;Password=NewPassw0rDP@ssw0rd2025!;Encrypt=True;TrustServerCertificate=True;
#try delete and run minikube for any sa password connection issues.