apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: kib-manual
  name: kibana-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kib-manual
  template:
    metadata:
      labels:
        app: kib-manual
    spec:
      containers:
      - image: docker.elastic.co/kibana/kibana:8.15.3
        name: kibana
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
        # livenessProbe:
        #   httpGet:
        #     port: http
        #     path: /status
        #   initialDelaySeconds: 40
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /status
        #     port: http
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kib-manual
  name: kibana-service
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: kib-manual
  type: NodePort

#Prerequisite: Execute Elasticsearch Deplotment 
#kubectl apply -f k8s-kibana-deployment.yaml
#kubectl port-forward kibana-logging-0 5601:5601
#Open a terminal on the POD where Elasticsearch is running.
#bin/elasticsearch-create-enrollment-token -s kibana --url "https://localhost:9200"
#navihate to kibana/bin and run 
#kibana-verification-code.bat or kibana-verification
#bin/elasticsearch-create-enrollment-token -s kibana

#kubectl exec -it kibana-logging-0 -- bash